var fs = require('fs');
var os = require('os');
var path = require('path');
var reader = require('../lib/reader.js');
var TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'sift-test-'));
fs.writeFileSync(path.join(TMP, 'good.csv'), 'a,b\n1,2\n');
var pattern = path.join(TMP, '*.csv');
console.log('TMP=', JSON.stringify(TMP));
console.log('pattern=', JSON.stringify(pattern));
console.log('isAbsolute=', path.isAbsolute(pattern));
console.log('sep=', JSON.stringify(path.sep));
console.log('driveMatch=', JSON.stringify(pattern.match(/^([a-zA-Z]:)[\\/]/)));
console.log('result=', JSON.stringify(reader.expandGlob(pattern)));
